### PR TITLE
Fix tests broken by making Node ID mandatory

### LINKED ISSUE #224: Fix tests left broken after making Node ID mandatory for events
Before the PR making Node IDs mandatory for events (https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/196), running the test suite resulted in: 
1128 tests, 4938 assertions, 34 failures, 35 errors, 10 skips
after the PR, at 369a6c1c0e3bbef369a140d9f68373fac2526bcf, we got
1128 tests, 4661 assertions, 82 failures, 46 errors, 10 skips
this is a difference of 48 failures and 11 errors. The purpose of this task is to fix the introduced failures and errors.

### PR DESCRIPTION
**Pull request by umunixie**
**Summary of changes**

- making more tests that create Events resilient to changes in mandatory fields overall (using fixtures or, as a fallback, the pre-existing `@mandatory` or `@mandatory_fields` variables)
- adding fixtures linking Nodes and Events
- changing some expected counts of associated nodes due to their number now being a minimum of 1 and not 0
- flat-out skipping the ingestors tests because (1) we're not using ingestors, (2) deleting the ingestors code and respective tests is fairly complicated since we want to leave the machinery of ingestors in, and the tests of that assume you're not removing any of the existing ingestors, (3) ingested events will never have all the fields we now consider mandatory
- removing the tests about locked fields, as we had removed this functionality but couldn't see these failing tests because of all the Node ID and Content Provider failures

**Motivation and context**

Closes #224. It gets the errors down to 0 and failures to 1. The last failure is in `NodeTest#test_can_get_resources_through_providers_and_directly_associated` which was modified in ff79b84908112 and I don't think it's related to making Node ID mandatory.

The code doesn't adhere to the style guide as there's no time to clean everything up.
 
**Checklist**

- [x] I have read and followed the [CONTRIBUTING](https://github.com/ElixirTeSS/TeSS/blob/master/CONTRIBUTING.md) guide.
- [x] I confirm that I have the authority necessary to make this contribution on behalf of its copyright owner and agree
  to license it to the TeSS codebase under the 
  [BSD license](https://github.com/ElixirTeSS/TeSS/blob/master/LICENSE).

### CODE REVIEW

File: app/controllers/nodes_controller.rb [hunk 1]
```diff
@@ -3,7 +3,6 @@ class NodesController < ApplicationController
   before_action :feature_enabled?
   before_action :set_node, only: [:show, :edit, :update, :destroy]
   before_action :set_breadcrumbs
-  before_action :redirect_to_root
```
Comment (adeel-ahmad-awan) [inline app/controllers/nodes_controller.rb:6]: are the requirements changed, or is this redirection no longer required

File: test/controllers/events_controller_test.rb [hunk 2]
```diff
@@ -881,54 +887,6 @@ class EventsControllerTest < ActionController::TestCase
     assert_includes assigns(:event).node_ids, nodes(:good).id
   end
 
-  test 'can lock fields' do
```
Comment (adeel-ahmad-awan) [inline test/controllers/events_controller_test.rb:884]: are these tests no longer required?

**Comment by adeel-ahmad-awan** [comment]
Overall, the changes look good. I’ve reviewed the code, and everything seems fine, although I haven’t had the chance to test the code myself.

**Review by adeel-ahmad-awan — DISMISSED** [review]
Overall, the changes look good. I’ve reviewed the code, and everything seems fine, although I haven’t had the chance to test it myself. There is just one minor comment I would like to mention.

File: app/controllers/nodes_controller.rb (hunk 1 above)
Comment (umunixie) [reply app/controllers/nodes_controller.rb:6]: have you seen the commit message? the relevant commit being f4ade84e030

Comment (adeel-ahmad-awan) [reply app/controllers/nodes_controller.rb:6]: As far as I remember, this redirection was originally added based on requirements from management. In your commit message, you mentioned that it breaks the API and isn’t the correct way to restrict access

That said, it looks like it was removed primarily to get the tests working. If that was the only reason, why wasn’t it reintroduced afterward in a more appropriate form?

Also, since you mentioned you weren’t sure about the original intention and had to guess, have you checked with anyone on the team to confirm why it was added?
- If access restriction is still needed, has it been implemented in a better way?
- And have you confirmed with the team (or management) that this redirection is no longer required?

Comment (umunixie) [reply app/controllers/nodes_controller.rb:6]: i'll have to go a bit meta here. the scope of the ticket is to fix the tests, and this has been done. it unblocked another ticket on which i'm currently working, and unfortunately i do not believe i'll be able to pick up more tickets in my remaining time here.

that said, if you see value in implementing access control in a conventional, framework-aligned way that doesn't break things, i agree it's a good idea and should be written down in a ticket which lays out the requirements you're talking about. or maybe there's already a ticket that explains them? i couldn't find one, but if it exists, it can be reopened.

Comment (adeel-ahmad-awan) [reply app/controllers/nodes_controller.rb:6]: I understand the focus was on getting the tests to pass, but if access control is still a requirement (as it was added based on management’s input), it shouldn’t be removed without a proper alternative in place. Even if the current implementation wasn’t ideal, removing it entirely without addressing the underlying need isn’t a safe approach.

Since there’s no existing ticket outlining the access control requirements, could you please create a new ticket with clear instructions on how this should be properly handled? Also, it would be helpful to leave a TODO comment in the code indicating that access control needs to be reimplemented appropriately.

Comment (umunixie) [reply app/controllers/nodes_controller.rb:6]: it would be nice if i had the time to dive into the requirements, discuss them, and write up an explanation on how to handle access control in Rails. but i don't! since we're not releasing on every commit, i see no risk in leaving this out of scope of this PR. after all, the API has been broken for quite a number of commits, and that wasn't a problem, dozens of tests were broken and failing for quite some time, and that wasn't a problem. seems odd to me to now draw a red line on Nodes API being like it had been before your changes.

Comment (adeel-ahmad-awan) [reply app/controllers/nodes_controller.rb:6]: Thank you for clarifying your stance, but I want to address the core issue here.

Our requirements explicitly called for blocking access to node routes for end users, and the code in question was a straightforward solution implemented to meet this need. though new test cases failures were introduced with this but then we had ticket for fixing that,

Even if I approve this PR as is, and the requirements remain unchanged, we will likely end up reintroducing the same code or creating a ticket to redo the effort.

I don’t believe this is about drawing a red line; rather, it’s about improving the codebase. While there were broken test cases, we were actively working on fixing them. For the end user, these broken tests are not visible or impactful, so they should not justify removing essential functionality.

@kristen-schroeder 
Could you please provide your input on this matter? It would be helpful to confirm whether access control for node routes remains a requirement from management and, if so, how you’d like us to proceed in implementing it.

Comment (kristen-schroeder) [reply app/controllers/nodes_controller.rb:6]: @adeel-ahmad-awan please approve the PR before Friday EOD.

***a small note that if i am summoned, a stakeholder summary would be very helpful in being able to provide input :). ive been trying to unpick what this all means for a while now and im still not sure if i have it straight, but ultimately time and priorities dictate that we need to move forward with this ASAP.

https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/issues/184
this is where it discusses blocking access to node routes for end users, and i'm assuming this 

> Disable node in the content provider.
> Disable node show page and it should be unclickable from the event page

is the user-facing behaviours this refers to? its fine if the users manage to get there for now, we can address cleaning this up after the release.

**Review by adeel-ahmad-awan — APPROVED** [review]
